name: build-app
on:
  push:
    branches:
      - feature/**
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
      - name: Install packages
        run: yarn install
      - name: Create build
        run: npm run build
      - name: Export version variable
        run: |
          echo "IMAGE_NAME=$(cat package.json | jq -r '(.name + "'":"'" + .version)')" >> "$GITHUB_ENV";
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} .